Repository adolfintel/OpenPods, pull requests merged in 2020-06, with the labels that each got.

#79 Ask for confirmation before hiding the app
  OpenPods/app/src/main/java/com/dosse/airpods/SettingsFragment.java
  OpenPods/app/src/main/res/values-de/strings.xml
  OpenPods/app/src/main/res/values/strings.xml
Labels: enhancement, translation

#84 Updated to latest gradle
  OpenPods/gradle/wrapper/gradle-wrapper.properties
Labels: minor

#91 Minor changes to MIUI Warning & Hebrew translation for new strings
  OpenPods/app/src/main/java/com/dosse/airpods/MainActivity.java
  OpenPods/app/src/main/res/values-iw-rIL/strings.xml
Labels: minor, miui-emui, translation
